version: '2'
services:
  nodered:
    image: gitpower2017/ctnodered
    ports:
      - "1880:1880"
    volumes:
      - ./data/nodered:/data
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    restart: always
    network_mode: "bridge"
